# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cbd4f7a7912222943a6fc6ee734f5c9ca17e3a09e2202a812d002284bb02369c8f09719b34e6dee3cde87dbe3459b1bc53f108a2db51f512a47dc1098c9009f

test:
  secret_key_base: 41619e7cf127e089cebe615785f8a8e873d3d7e353b8bf7d71251f41962e3d5e15dbabe5271f6d4e816804c84a391b018298fd4f98f58a89f995972b8c3afc5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
